# Generated by Django 4.0 on 2022-03-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.ImageField(upload_to='', verbose_name='image')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('types', models.CharField(max_length=255, verbose_name='type')),
                ('sizes', models.IntegerField(verbose_name='size')),
                ('price', models.IntegerField(verbose_name='price')),
                ('category', models.CharField(max_length=255, verbose_name='category')),
                ('rating', models.IntegerField(verbose_name='rating')),
            ],
        ),
    ]
