# Generated by Django 4.0 on 2022-03-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='mas',
            field=models.FileField(null=True, upload_to='', verbose_name='mas'),
        ),
    ]
