# Generated by Django 4.0 on 2022-03-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactview', '0002_pizza_mas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='mas',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.IntegerField(verbose_name='category'),
        ),
    ]
