# Generated by Django 4.0 on 2022-03-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactview', '0003_remove_pizza_mas_alter_pizza_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_pizza', models.CharField(max_length=50, verbose_name='Тип пиццы')),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='types',
        ),
        migrations.AddField(
            model_name='pizza',
            name='types',
            field=models.ManyToManyField(related_name='typesOfpizzas', to='reactview.Type', verbose_name='Тип'),
        ),
    ]
