# Generated by Django 4.0 on 2022-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactview', '0004_type_remove_pizza_types_pizza_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Размеры пиццы',
                'verbose_name_plural': 'Размеры пиццы',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['-id'], 'verbose_name': 'Пиццы', 'verbose_name_plural': 'Пиццы'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['-id'], 'verbose_name': 'Тип пиццы', 'verbose_name_plural': 'Тип пиццы'},
        ),
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.IntegerField(verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='imageUrl',
            field=models.ImageField(upload_to='', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='rating',
            field=models.IntegerField(verbose_name='рейтинг'),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='sizes',
        ),
        migrations.AddField(
            model_name='pizza',
            name='sizes',
            field=models.ManyToManyField(related_name='sizeOfpizza', to='reactview.Size', verbose_name='Размеры'),
        ),
    ]
